/*
    Creates the normalized company tables.
    Run against the database referenced by the "AppConnection" connection string.
    Idempotent: safe to run multiple times.

    Table names are PLURAL to match EF Core's DbSet-name convention
    (DbSet<Company> Companies, DbSet<UserCompany> UserCompanies), and quoted because
    PostgreSQL folds unquoted identifiers to lower case while EF Core quotes them.
*/

BEGIN;

-------------------------------------------------------------------------------
-- Case-insensitive collation (AppDbContext.CaseInsensitiveCollation)
-------------------------------------------------------------------------------
-- PostgreSQL compares text case-sensitively; this ICU collation makes "Acme" and
-- "acme" the same company name, for lookups and for the unique index below.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_collation WHERE collname = 'case_insensitive') THEN
        CREATE COLLATION public.case_insensitive (
            provider = icu, locale = 'und-u-ks-level2', deterministic = false);
    END IF;
END $$;

-------------------------------------------------------------------------------
-- Companies
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public."Companies" (
    "CompanyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"      character varying(256) COLLATE public.case_insensitive NOT NULL,
    CONSTRAINT "PK_Companies" PRIMARY KEY ("CompanyId")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Companies_Name"
    ON public."Companies" ("Name");

-------------------------------------------------------------------------------
-- UserCompanies
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public."UserCompanies" (
    "UserId"    uuid    NOT NULL,
    "CompanyId" integer NOT NULL,
    CONSTRAINT "PK_UserCompanies" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_UserCompanies_Companies" FOREIGN KEY ("CompanyId")
        REFERENCES public."Companies" ("CompanyId")
);

-- Optional DB-level FK to identity users (same physical database, cross-schema).
DO $$
BEGIN
    IF to_regclass('identity."AspNetUsers"') IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM pg_constraint
                       WHERE conname = 'FK_UserCompanies_AspNetUsers') THEN
        ALTER TABLE public."UserCompanies"
            ADD CONSTRAINT "FK_UserCompanies_AspNetUsers" FOREIGN KEY ("UserId")
                REFERENCES identity."AspNetUsers" ("Id");
    END IF;
END $$;

COMMIT;
