/*
    Identity database objects for StarterApp.

    Target:   PostgreSQL 14+
    Context:  AppIdentityDbContext (IdentityDbContext<ApplicationUser, ApplicationRole, Guid>)
    Schema:   identity
    Keys:     uuid (Guid)

    Equivalent to the InitialIdentity EF Core migration, for environments where schema
    changes are applied by hand rather than with 'dotnet ef database update'. It records
    that migration in identity."__EFMigrationsHistory", so the two approaches can be mixed:
    later migrations apply on top of a database this script created.

    Idempotent: every object is created only if it does not already exist, so it is safe
    to re-run. Run it against the database referenced by the "IdentityConnection"
    connection string, e.g. psql "$IDENTITY_CONNECTION" -f Identity_CreateObjects.sql
*/

BEGIN;

CREATE SCHEMA IF NOT EXISTS identity;

-------------------------------------------------------------------------------
-- AspNetRoles
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."AspNetRoles" (
    "Id"               uuid                   NOT NULL,
    "Name"             character varying(256),
    "NormalizedName"   character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
    ON identity."AspNetRoles" ("NormalizedName");

-------------------------------------------------------------------------------
-- AspNetUsers  (includes the custom FullName and IsActive columns)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."AspNetUsers" (
    "Id"                   uuid                     NOT NULL,
    "FullName"             text                     NOT NULL,
    "IsActive"             boolean                  NOT NULL DEFAULT true,
    "UserName"             character varying(256),
    "NormalizedUserName"   character varying(256),
    "Email"                character varying(256),
    "NormalizedEmail"      character varying(256),
    "EmailConfirmed"       boolean                  NOT NULL,
    "PasswordHash"         text,
    "SecurityStamp"        text,
    "ConcurrencyStamp"     text,
    "PhoneNumber"          text,
    "PhoneNumberConfirmed" boolean                  NOT NULL,
    "TwoFactorEnabled"     boolean                  NOT NULL,
    "LockoutEnd"           timestamp with time zone,
    "LockoutEnabled"       boolean                  NOT NULL,
    "AccessFailedCount"    integer                  NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "EmailIndex"
    ON identity."AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
    ON identity."AspNetUsers" ("NormalizedUserName");

-------------------------------------------------------------------------------
-- AspNetRoleClaims
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."AspNetRoleClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId"     uuid    NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES identity."AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId"
    ON identity."AspNetRoleClaims" ("RoleId");

-------------------------------------------------------------------------------
-- AspNetUserClaims
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."AspNetUserClaims" (
    "Id"         integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"     uuid    NOT NULL,
    "ClaimType"  text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES identity."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId"
    ON identity."AspNetUserClaims" ("UserId");

-------------------------------------------------------------------------------
-- AspNetUserLogins
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."AspNetUserLogins" (
    "LoginProvider"       text NOT NULL,
    "ProviderKey"         text NOT NULL,
    "ProviderDisplayName" text,
    "UserId"              uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES identity."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId"
    ON identity."AspNetUserLogins" ("UserId");

-------------------------------------------------------------------------------
-- AspNetUserRoles
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES identity."AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES identity."AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId"
    ON identity."AspNetUserRoles" ("RoleId");

-------------------------------------------------------------------------------
-- AspNetUserTokens
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."AspNetUserTokens" (
    "UserId"        uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name"          text NOT NULL,
    "Value"         text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId")
        REFERENCES identity."AspNetUsers" ("Id") ON DELETE CASCADE
);

-------------------------------------------------------------------------------
-- EF Core migrations history (matches the MigrationsHistoryTable configuration)
-------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS identity."__EFMigrationsHistory" (
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- Marks InitialIdentity as applied so 'dotnet ef database update' does not re-create
-- these tables. Keep the id in step with Data/Migrations/Identity if you regenerate it.
INSERT INTO identity."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260925233810_InitialIdentity', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;
